apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: digitalocean
  namespace: {{ .Values.config.namespace | default .Release.Namespace | trunc 63 }}
spec:
  version: v1.6.0
  {{- if .Values.config.secret.name }}
  configSecret:
    name: {{ .Values.config.secret.name }}
    namespace: {{ .Values.config.namespace | default .Release.Namespace | trunc 63 }}
  {{- end }}